-- TIBOX Compliance — importación del catálogo creado por Paula en SharePoint
-- Ejecutar DESPUÉS de 20260826120000_initial_mvp.sql
-- Carga el contenido funcional al tenant de demostración `cliente-demo`.
-- Los KPIs de `Resumen Ejecutivo.csv` NO se persisten porque eran valores estáticos
-- y no coinciden con los estados exportados; la aplicación los calcula dinámicamente.

begin;

do $$
declare
  v_org uuid;
begin
  insert into public.organizations (name, slug, status, is_internal)
  values ('Cliente Demo', 'cliente-demo', 'active', false)
  on conflict (slug) do update set name = excluded.name, status = 'active';

  select id into v_org from public.organizations where slug = 'cliente-demo';

  -- Reemplazar solo el catálogo/demo funcional de esta organización.
  delete from public.compliance_modules where organization_id = v_org;
  delete from public.security_categories where organization_id = v_org;

  -- 9 módulos definidos en SharePoint.
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M01', 'Información y transparencia', 'Inventario, finalidades, bases legales, destinatarios, conservación y política de tratamiento.', 'Arts. 14 y 14 ter', 1);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M02', 'Derechos de titulares', 'Procedimientos y evidencias para gestionar solicitudes de acceso, rectificación, supresión, oposición, portabilidad y bloqueo.', 'Arts. 4 a 11', 2);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M03', 'Seguridad y confidencialidad', 'Controles técnicos y organizativos para proteger la confidencialidad, integridad, disponibilidad y resiliencia de los datos personales.', 'Arts. 14 bis y 14 quinquies', 3);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M04', 'Incidentes y vulneraciones', 'Registro, procedimiento y evidencias para detectar, analizar, gestionar y documentar incidentes que afecten datos personales.', 'Art. 14 sexies', 4);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M05', 'Privacidad desde el diseño', 'Controles de privacidad incorporados desde el diseño de nuevos sistemas, procesos y tratamientos.', 'Art. 14 quáter', 5);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M06', 'Terceros y encargados de tratamiento', 'Registro, contratos y evaluación de proveedores o terceros que tratan datos personales por cuenta de la organización.', 'Art. 15 bis', 6);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M07', 'Evaluaciones de impacto', 'Evaluaciones de tratamientos que puedan generar alto riesgo para los derechos de los titulares y sus medidas de mitigación.', 'Art. 15 ter', 7);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M08', 'Prevención y cumplimiento', 'Acciones preventivas, controles y documentación asociada al programa de cumplimiento y prevención de infracciones.', 'Arts. 48 y 49', 8);
  insert into public.compliance_modules (organization_id, module_key, name, description, legal_reference, sort_order) values (v_org, 'M09', 'Seguridad de Infraestructura y Aplicaciones', 'Assessment técnico de controles básicos y avanzados sobre servidores, endpoints, correo, firewall, backup y aplicaciones.', 'Assessment técnico', 9);

  -- 24 obligaciones/evidencias solicitadas.
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-001', 'Procedimiento de atención de derechos', 'Procedimiento para recibir, validar, gestionar y responder solicitudes de acceso, rectificación, supresión, oposición, portabilidad y bloqueo.', 'Arts. 4 a 11', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Derechos de titulares';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-002', 'Registro de solicitudes de titulares', 'Registro de solicitudes recibidas, fechas de ingreso, responsable, acciones realizadas, respuesta y cierre.', 'Arts. 4 a 11', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Derechos de titulares';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-003', 'Formulario o canal de atención', 'Evidencia del canal habilitado para que los titulares puedan ejercer sus derechos y realizar solicitudes.', 'Arts. 4 a 11', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Derechos de titulares';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-004', 'Metodología DPIA', 'Criterios y metodología para identificar cuándo un tratamiento puede producir alto riesgo y requiere una evaluación de impacto.', 'Art. 15 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Evaluaciones de impacto';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-005', 'Evaluación de impacto', 'Documento que analiza el tratamiento, riesgos para los titulares y medidas definidas para reducir o gestionar dichos riesgos.', 'Art. 15 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Evaluaciones de impacto';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-006', 'Aprobación o revisión del DPIA', 'Evidencia de revisión, validación y aprobación interna de la evaluación de impacto correspondiente.', 'Art. 15 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Evaluaciones de impacto';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-007', 'Procedimiento de incidentes', 'Procedimiento para detectar, escalar, analizar, contener, notificar y cerrar incidentes o vulneraciones que afecten datos personales.', 'Art. 14 sexies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Incidentes y vulneraciones';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-008', 'Registro de vulneraciones', 'Registro histórico de incidentes, naturaleza, efectos, categorías de datos o titulares afectados, medidas adoptadas y estado de cierre.', 'Art. 14 sexies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Incidentes y vulneraciones';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-009', 'Plantilla de notificación de incidentes', 'Formato interno para documentar los antecedentes necesarios y preparar comunicaciones o notificaciones cuando corresponda.', 'Art. 14 sexies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Incidentes y vulneraciones';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-010', 'Inventario de tratamientos', 'Matriz que identifica las actividades de tratamiento de datos personales, titulares, categorías de datos, finalidad, base de legitimidad, sistemas, terceros y períodos de conservación.', 'Arts. 14 y 14 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Información y transparencia';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-011', 'Política de tratamiento de datos', 'Documento corporativo que define cómo la organización trata los datos personales, sus principios, responsabilidades y mecanismos de información a los titulares.', 'Arts. 14 y 14 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Información y transparencia';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-012', 'Matriz de información pública', 'Documento que consolida la información que debe mantenerse disponible al público respecto de los tratamientos de datos personales.', 'Arts. 14 y 14 ter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Información y transparencia';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-013', 'Plan de prevención de infracciones', 'Documento con acciones preventivas, controles, responsables y medidas destinadas a reducir el riesgo de infracciones.', 'Arts. 48 y 49', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Prevención y cumplimiento';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-014', 'Programa de cumplimiento', 'Documentación del modelo voluntario de prevención y programa de cumplimiento, cuando la organización decida implementarlo.', 'Arts. 48 y 49', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Prevención y cumplimiento';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-015', 'Registro de capacitaciones', 'Evidencia de actividades de capacitación y sensibilización en protección de datos personales realizadas a colaboradores y responsables.', 'Arts. 48 y 49', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Prevención y cumplimiento';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-016', 'Checklist de privacidad para proyectos', 'Lista de revisión previa para nuevos sistemas, procesos, proyectos o tratamientos que involucren datos personales.', 'Art. 14 quáter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Privacidad desde el diseño';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-017', 'Ficha de evaluación de nuevo tratamiento', 'Documento para revisar finalidad, minimización, accesos, conservación y controles antes de implementar un nuevo tratamiento.', 'Art. 14 quáter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Privacidad desde el diseño';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-018', 'Aprobación de privacidad', 'Evidencia de revisión y aprobación interna de privacidad antes de poner en operación un nuevo tratamiento o cambio relevante.', 'Art. 14 quáter', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Privacidad desde el diseño';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-019', 'Matriz de controles de seguridad', 'Matriz que identifica los controles técnicos y organizativos implementados para proteger la confidencialidad, integridad, disponibilidad y resiliencia de los datos personales.', 'Arts. 14 bis y 14 quinquies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Seguridad y confidencialidad';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-020', 'Procedimiento de control de accesos', 'Procedimiento para asignar, revisar, modificar y revocar accesos a sistemas y repositorios que contienen datos personales.', 'Arts. 14 bis y 14 quinquies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Seguridad y confidencialidad';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-021', 'Evidencia de revisiones de seguridad', 'Reportes, actas o registros que acrediten la revisión periódica de controles de seguridad aplicables a datos personales.', 'Arts. 14 bis y 14 quinquies', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Seguridad y confidencialidad';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-022', 'Registro de encargados', 'Listado de proveedores o terceros que tratan datos por cuenta de la organización, indicando servicio, datos involucrados y estado contractual.', 'Art. 15 bis', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Terceros y encargados de tratamiento';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-023', 'Anexo o cláusula de tratamiento', 'Documento contractual que define las instrucciones, obligaciones y condiciones aplicables al tratamiento de datos realizado por un tercero.', 'Art. 15 bis', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Terceros y encargados de tratamiento';
  insert into public.obligations (organization_id, module_id, code, title, description, legal_reference, status, priority) select v_org, m.id, 'OBL-024', 'Evaluación de proveedor', 'Evaluación de privacidad y seguridad del proveedor, incluyendo los controles relevantes para el tratamiento de datos personales.', 'Art. 15 bis', 'pending', 'medium' from public.compliance_modules m where m.organization_id = v_org and m.name = 'Terceros y encargados de tratamiento';

  -- 7 categorías del assessment técnico.
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Servidores', 'servidores', 1);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'PCs / Endpoints', 'pcs-endpoints', 2);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Correo / Microsoft 365', 'correo-microsoft-365', 3);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Firewall / Red', 'firewall-red', 4);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Backup / Continuidad', 'backup-continuidad', 5);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Aplicaciones SaaS / Bsale', 'aplicaciones-saas-bsale', 6);
  insert into public.security_categories (organization_id, name, slug, sort_order) values (v_org, 'Aplicaciones internas / ERP / CRM', 'aplicaciones-internas-erp-crm', 7);

  -- 58 controles de seguridad. Los títulos repetidos se mantienen porque pertenecen a categorías distintas.
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-001', 'Usuarios y roles', 'Verificar cuentas individuales y permisos asociados al rol o función de cada usuario.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-002', 'Contraseñas y autenticación', 'Revisar políticas de autenticación y habilitar MFA cuando esté disponible.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-003', 'Bajas y cambios de rol', 'Mantener un procedimiento para retirar o modificar accesos ante bajas, traslados o cambios de función.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-004', 'Backups', 'Validar respaldo de bases de datos o información crítica y realizar pruebas de recuperación.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-005', 'Parches de aplicación', 'Mantener versiones soportadas y gestionar vulnerabilidades conocidas de la aplicación y sus componentes.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-006', 'Logs y trazabilidad', 'Registrar accesos, cambios relevantes, errores y acciones administrativas para apoyar monitoreo e investigación.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-007', 'Separación de ambientes', 'Separar desarrollo, pruebas y producción, evitando usar datos personales reales cuando no sea estrictamente necesario.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-008', 'Gestión de vulnerabilidades', 'Realizar revisiones periódicas, pentest o escaneo de vulnerabilidades y mantener un plan de remediación.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones internas / ERP / CRM';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-009', 'Usuarios y permisos', 'Revisar usuarios, roles y permisos en aplicaciones SaaS o Bsale y limitar accesos según necesidad.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-010', 'Bajas de usuarios', 'Retirar oportunamente accesos de usuarios que ya no requieren ingresar a la aplicación.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-011', 'MFA', 'Habilitar autenticación multifactor en aplicaciones que lo soporten, especialmente para perfiles administrativos.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-012', 'Integraciones y API', 'Inventariar integraciones, tokens, API keys y cuentas técnicas utilizadas por las aplicaciones SaaS.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-013', 'Exportación de datos', 'Controlar quién puede exportar información y revisar mecanismos para evitar exposición no autorizada de datos personales.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-014', 'Logs de auditoría', 'Habilitar y revisar logs de actividad administrativa y accesos cuando la plataforma los ofrezca.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-015', 'Retención y eliminación', 'Configurar o documentar períodos de retención y procedimientos de eliminación de datos cuando la plataforma lo permita.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-016', 'Revisión del proveedor SaaS', 'Evaluar seguridad, privacidad, ubicación de datos y compromisos contractuales del proveedor de la aplicación.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Aplicaciones SaaS / Bsale';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-017', 'Inventario de respaldos', 'Identificar sistemas y datos respaldados, frecuencia, destino y responsable de cada respaldo.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-018', 'Retención de backups', 'Definir y aplicar períodos de retención coherentes con los requerimientos operacionales y legales.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-019', 'Pruebas de restauración', 'Realizar pruebas periódicas de restauración y conservar evidencia del resultado.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-020', 'Protección del repositorio', 'Restringir el acceso a respaldos y protegerlos frente a borrado, ransomware o modificación no autorizada.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-021', 'Copia externa o inmutable', 'Mantener al menos una copia externa, aislada o inmutable para sistemas críticos.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-022', 'Plan de continuidad', 'Documentar prioridades, responsables, RTO/RPO y procedimientos de recuperación para servicios críticos.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-023', 'Prueba de continuidad', 'Ejecutar ejercicios o simulaciones periódicas de recuperación y continuidad.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Backup / Continuidad';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-024', 'Reglas de acceso', 'Revisar reglas de firewall, ACL y segmentación para limitar exposición y comunicaciones innecesarias.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-025', 'Acceso remoto', 'Asegurar que el acceso remoto administrativo use VPN u otro canal seguro, con MFA cuando sea posible.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-026', 'Administración del firewall', 'Restringir el acceso administrativo, mantener cuentas individuales y revisar cambios de configuración.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-027', 'Actualizaciones de firmware', 'Mantener firewall, switches, routers y otros dispositivos de red con versiones soportadas y parches vigentes.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-028', 'Segmentación de red', 'Separar redes de usuarios, servidores, invitados, IoT y administración cuando corresponda al riesgo.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-029', 'Monitoreo y alertas', 'Habilitar registros, alertas o monitoreo de eventos de seguridad relevantes en la infraestructura de red.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-030', 'IDS / IPS', 'Evaluar o habilitar capacidades de detección y prevención de intrusiones según la criticidad de los servicios.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-031', 'Revisión periódica de reglas', 'Realizar revisiones periódicas para eliminar reglas obsoletas, amplias o sin justificación.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Firewall / Red';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-032', 'MFA administradores', 'Exigir MFA para cuentas administrativas y privilegiadas de Microsoft 365.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-033', 'MFA usuarios', 'Extender MFA a todos los usuarios y revisar excepciones justificadas.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-034', 'Bajas de usuarios', 'Validar proceso formal para bloquear cuentas, revocar sesiones y retirar accesos al finalizar una relación laboral o contractual.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-035', 'Cuentas privilegiadas', 'Separar cuentas administrativas de las cuentas de uso diario y limitar el número de administradores globales.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-036', 'Protección antiphishing', 'Configurar políticas antiphishing, antispam y protección de enlaces/adjuntos según las licencias disponibles.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-037', 'Reenvío externo', 'Controlar reglas de reenvío automático hacia dominios externos y detectar configuraciones anómalas.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-038', 'Acceso condicional', 'Aplicar políticas de acceso condicional basadas en riesgo, ubicación, dispositivo o aplicación cuando la licencia lo permita.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-039', 'Auditoría unificada', 'Habilitar y conservar registros de auditoría relevantes para investigar accesos y cambios.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-040', 'Etiquetas y protección de información', 'Evaluar clasificación, etiquetado y protección de información sensible según el uso de Microsoft Purview u otras capacidades.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Correo / Microsoft 365';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-041', 'Inventario de equipos', 'Mantener inventario actualizado de notebooks y PCs, usuario asignado, sistema operativo y estado.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-042', 'Antivirus / EDR', 'Validar protección antimalware o EDR instalada, activa y administrada en los equipos.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-043', 'Actualizaciones', 'Mantener sistema operativo y aplicaciones con actualizaciones de seguridad vigentes.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-044', 'Bloqueo de pantalla', 'Configurar bloqueo automático de sesión y requerir autenticación para reanudar.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-045', 'Privilegios locales', 'Restringir privilegios de administrador local y evitar su uso cotidiano.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-046', 'Cifrado de disco', 'Habilitar cifrado de disco en equipos que almacenen o accedan a información sensible.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-047', 'MDM / administración central', 'Administrar configuraciones y cumplimiento de endpoints mediante una plataforma central cuando corresponda.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-048', 'Control de dispositivos externos', 'Gestionar uso de USB, discos externos y otros medios removibles según el nivel de riesgo.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-049', 'Borrado seguro', 'Definir procedimiento de borrado seguro para equipos reasignados, devueltos o dados de baja.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'PCs / Endpoints';

  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-050', 'Inventario de servidores', 'Mantener inventario actualizado de servidores físicos, virtuales y servicios críticos.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-051', 'Antivirus / EDR', 'Validar que exista protección antimalware o EDR activa, administrada y con alertas habilitadas.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-052', 'Parches y actualizaciones', 'Mantener sistemas operativos, hipervisores y servicios con parches de seguridad vigentes.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-053', 'Acceso administrativo', 'Restringir accesos administrativos a cuentas autorizadas, registrar actividad y evitar cuentas compartidas.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-054', 'Backups de servidores', 'Validar cobertura de respaldo de servidores y datos críticos, frecuencia y pruebas de recuperación.', 'basic', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-055', 'Hardening', 'Aplicar configuraciones seguras, deshabilitar servicios innecesarios y reducir superficie de ataque.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-056', 'Segmentación de servidores', 'Aislar servidores críticos y limitar comunicaciones según funciones y necesidades operacionales.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-057', 'Logs centralizados', 'Centralizar o conservar logs de seguridad relevantes para detección e investigación de incidentes.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';
  insert into public.security_controls (organization_id, category_id, code, title, description, level, status, recommendation, notes) select v_org, c.id, 'SEC-058', 'Monitoreo de disponibilidad y seguridad', 'Monitorear disponibilidad, capacidad y eventos de seguridad de servidores y servicios críticos.', 'advanced', 'pending', null, null from public.security_categories c where c.organization_id = v_org and c.name = 'Servidores';

  insert into public.audit_events (organization_id, actor_user_id, action, entity_type, metadata)
  values (v_org, null, 'catalog.imported', 'organization', jsonb_build_object(
    'source', 'Paula SharePoint export',
    'modules', 9,
    'obligations', 24,
    'security_categories', 7,
    'security_controls', 58,
    'note', 'Adjuntos no incluidos: los CSV solo contienen contador de adjuntos.'
  ));
end $$;

commit;
